# Build environment: kominka:core + busybox (full utils) + binutils-strip + make.
# Used by CI for all zig-cc package builds.

FROM kominka:core

ARG REPO_URL=https://kominka.17166969.xyz
ENV LD_LIBRARY_PATH=/usr/lib \
    LOGNAME=root
RUN KOMINKA_REPO=${REPO_URL} \
    R2_PUBLIC_URL=https://pub-15b3a4c25627476493c0e1a68993f4d8.r2.dev \
    /usr/local/bin/ysh -c 'pm i busybox binutils-strip make'
