#ifndef __ASM_CPUCAP_DEFS_H
#define __ASM_CPUCAP_DEFS_H

/* Generated file - do not edit */

#define ARM64_ALWAYS_BOOT                             	0
#define ARM64_ALWAYS_SYSTEM                           	1
#define ARM64_BTI                                     	2
#define ARM64_HAS_32BIT_EL0_DO_NOT_USE                	3
#define ARM64_HAS_32BIT_EL1                           	4
#define ARM64_HAS_ADDRESS_AUTH                        	5
#define ARM64_HAS_ADDRESS_AUTH_ARCH_QARMA3            	6
#define ARM64_HAS_ADDRESS_AUTH_ARCH_QARMA5            	7
#define ARM64_HAS_ADDRESS_AUTH_IMP_DEF                	8
#define ARM64_HAS_AMU_EXTN                            	9
#define ARM64_HAS_ARMv8_4_TTL                         	10
#define ARM64_HAS_CACHE_DIC                           	11
#define ARM64_HAS_CACHE_IDC                           	12
#define ARM64_HAS_CNP                                 	13
#define ARM64_HAS_CRC32                               	14
#define ARM64_HAS_DCPODP                              	15
#define ARM64_HAS_DCPOP                               	16
#define ARM64_HAS_DIT                                 	17
#define ARM64_HAS_E0PD                                	18
#define ARM64_HAS_ECV                                 	19
#define ARM64_HAS_ECV_CNTPOFF                         	20
#define ARM64_HAS_EPAN                                	21
#define ARM64_HAS_EVT                                 	22
#define ARM64_HAS_FPMR                                	23
#define ARM64_HAS_FGT                                 	24
#define ARM64_HAS_FGT2                                	25
#define ARM64_HAS_FPSIMD                              	26
#define ARM64_HAS_GCS                                 	27
#define ARM64_HAS_GENERIC_AUTH                        	28
#define ARM64_HAS_GENERIC_AUTH_ARCH_QARMA3            	29
#define ARM64_HAS_GENERIC_AUTH_ARCH_QARMA5            	30
#define ARM64_HAS_GENERIC_AUTH_IMP_DEF                	31
#define ARM64_HAS_GICV3_CPUIF                         	32
#define ARM64_HAS_GICV5_CPUIF                         	33
#define ARM64_HAS_GICV5_LEGACY                        	34
#define ARM64_HAS_GIC_PRIO_MASKING                    	35
#define ARM64_HAS_GIC_PRIO_RELAXED_SYNC               	36
#define ARM64_HAS_ICH_HCR_EL2_TDIR                    	37
#define ARM64_HAS_HCR_NV1                             	38
#define ARM64_HAS_HCX                                 	39
#define ARM64_HAS_LDAPR                               	40
#define ARM64_HAS_LPA2                                	41
#define ARM64_HAS_LSE_ATOMICS                         	42
#define ARM64_HAS_MOPS                                	43
#define ARM64_HAS_NESTED_VIRT                         	44
#define ARM64_HAS_BBML2_NOABORT                       	45
#define ARM64_HAS_PAN                                 	46
#define ARM64_HAS_PMUV3                               	47
#define ARM64_HAS_S1PIE                               	48
#define ARM64_HAS_S1POE                               	49
#define ARM64_HAS_SCTLR2                              	50
#define ARM64_HAS_RAS_EXTN                            	51
#define ARM64_HAS_RASV1P1_EXTN                        	52
#define ARM64_HAS_RNG                                 	53
#define ARM64_HAS_SB                                  	54
#define ARM64_HAS_STAGE2_FWB                          	55
#define ARM64_HAS_TCR2                                	56
#define ARM64_HAS_TIDCP1                              	57
#define ARM64_HAS_TLB_RANGE                           	58
#define ARM64_HAS_VA52                                	59
#define ARM64_HAS_VIRT_HOST_EXTN                      	60
#define ARM64_HAS_WFXT                                	61
#define ARM64_HAS_XNX                                 	62
#define ARM64_HAFT                                    	63
#define ARM64_HW_DBM                                  	64
#define ARM64_KVM_HVHE                                	65
#define ARM64_KVM_PROTECTED_MODE                      	66
#define ARM64_MISMATCHED_CACHE_TYPE                   	67
#define ARM64_MPAM                                    	68
#define ARM64_MPAM_HCR                                	69
#define ARM64_MTE                                     	70
#define ARM64_MTE_ASYMM                               	71
#define ARM64_MTE_FAR                                 	72
#define ARM64_MTE_STORE_ONLY                          	73
#define ARM64_SME                                     	74
#define ARM64_SME_FA64                                	75
#define ARM64_SME2                                    	76
#define ARM64_SPECTRE_V2                              	77
#define ARM64_SPECTRE_V3A                             	78
#define ARM64_SPECTRE_V4                              	79
#define ARM64_SPECTRE_BHB                             	80
#define ARM64_SSBS                                    	81
#define ARM64_SVE                                     	82
#define ARM64_UNMAP_KERNEL_AT_EL0                     	83
#define ARM64_WORKAROUND_834220                       	84
#define ARM64_WORKAROUND_843419                       	85
#define ARM64_WORKAROUND_845719                       	86
#define ARM64_WORKAROUND_858921                       	87
#define ARM64_WORKAROUND_1418040                      	88
#define ARM64_WORKAROUND_1463225                      	89
#define ARM64_WORKAROUND_1508412                      	90
#define ARM64_WORKAROUND_1542419                      	91
#define ARM64_WORKAROUND_1742098                      	92
#define ARM64_WORKAROUND_1902691                      	93
#define ARM64_WORKAROUND_2038923                      	94
#define ARM64_WORKAROUND_2064142                      	95
#define ARM64_WORKAROUND_2077057                      	96
#define ARM64_WORKAROUND_2457168                      	97
#define ARM64_WORKAROUND_2645198                      	98
#define ARM64_WORKAROUND_2658417                      	99
#define ARM64_WORKAROUND_AMPERE_AC03_CPU_38           	100
#define ARM64_WORKAROUND_AMPERE_AC04_CPU_23           	101
#define ARM64_WORKAROUND_TRBE_OVERWRITE_FILL_MODE     	102
#define ARM64_WORKAROUND_TSB_FLUSH_FAILURE            	103
#define ARM64_WORKAROUND_TRBE_WRITE_OUT_OF_RANGE      	104
#define ARM64_WORKAROUND_CAVIUM_23154                 	105
#define ARM64_WORKAROUND_CAVIUM_27456                 	106
#define ARM64_WORKAROUND_CAVIUM_30115                 	107
#define ARM64_WORKAROUND_CAVIUM_TX2_219_PRFM          	108
#define ARM64_WORKAROUND_CAVIUM_TX2_219_TVM           	109
#define ARM64_WORKAROUND_CLEAN_CACHE                  	110
#define ARM64_WORKAROUND_DEVICE_LOAD_ACQUIRE          	111
#define ARM64_WORKAROUND_NVIDIA_CARMEL_CNP            	112
#define ARM64_WORKAROUND_PMUV3_IMPDEF_TRAPS           	113
#define ARM64_WORKAROUND_QCOM_FALKOR_E1003            	114
#define ARM64_WORKAROUND_QCOM_ORYON_CNTVOFF           	115
#define ARM64_WORKAROUND_REPEAT_TLBI                  	116
#define ARM64_WORKAROUND_SPECULATIVE_AT               	117
#define ARM64_WORKAROUND_SPECULATIVE_SSBS             	118
#define ARM64_WORKAROUND_SPECULATIVE_UNPRIV_LOAD      	119
#define ARM64_NCAPS					120

#endif /* __ASM_CPUCAP_DEFS_H */
